#! /usr/bin/env python3

import argparse
import os
import json

sections = {}
sections["sections"] = []
storedPath = "/home/ahacad/.distor/stored.json"
deprecatedPath = "/home/ahacad/.distor/deprecated.json"


class colors:
    BLACK = "\033[0;30m"        # Black
    RED = "\033[0;31m"          # Red
    GREEN = "\033[0;32m"        # Green
    YELLOW = "\033[0;33m"       # Yellow
    BLUE = "\033[0;34m"         # Blue
    PURPLE = "\033[0;35m"       # Purple
    CYAN = "\033[0;36m"         # Cyan
    WHITE = "\033[0;37m"        # White
    RESET = "\033[0;0m"
    BOLD = "\033[;1m"
    REVERSE = "\033[;7m""]"


def loadSection():
    """load sections from the stored json file
    """
    with open(storedPath) as json_file:
        sections = json.load(json_file)
    return sections


def writeEntry():
    """store entries to the path
    """
    with open(storedPath, "w") as outfile:
        json.dump(sections, outfile)


def addEntry(number, name, project, timeEstimation, DDL, remarks):
    """add an entry to the existing pool
    """
    sections["sections"].append({
        "Number": number,
        "Name": name,
        "Project": project,
        "Time Estimation": timeEstimation,
        "DDL": DDL,
        "Remarks": remarks
        })
    return 0


def deprecateEntry():
    """remove the entry from the existing pool and add to the deprecated pool

    """
    pass


def modifyEntry():
    """modify some specific entries
    """
    pass


def printEntry(width=20):
    """print the entries in the existing pool, you can choose the way to display
    """
    print(f"|{'SECTION NAME':^{width}}|{'PROJECT NAME':^{width}}|" +
          f"{'TIME ESTIMATED':^{width}}|{'DDL':^{width}}|" +
          f"{'REMARKS':^{width}}|")
    for section in sections["sections"]:
        name = section["Name"]
        project = section["Project"]
        timeEstimation = section["Time Estimation"]
        DDL = section["DDL"]
        remarks = section["Remarks"]
        print(f"|{colors.GREEN}{name:^{width}}{colors.RESET}|" +
              f"{colors.YELLOW}{project:^{width}}{colors.RESET}|" +
              f"{colors.BLUE}{timeEstimation:^{width}}{colors.RESET}|" +
              f"{colors.CYAN}{DDL:^{width}}{colors.RESET}|" +
              f"{colors.PURPLE}{remarks:^{width}}{colors.RESET}|")
    return 0


class sortFuncs:
    def sortByDDL(x):
        """sort the """
        return x['DDL']


def sortEntry(choice="DDL"):
    """sort entry
    """
    global sections
    if choice == "DDL":
        sections["sections"].sort(key=sortFuncs.sortByDDL)
    else:
        pass


def estimateTime():
    # how the time remained is calculated?
    """estimate whether you can make it before ddl
    """
    pass


def cli():
    """the command line interface
    """
    parser = argparse.ArgumentParser(description="distor")
    parser.add_argument("-a", nargs=6, help="please add: Number, Name" +
                        " of the section, Project name, " +
                        "Time Estimation, DDL, and remarks (6 pa" +
                        "remeters)")
    args = parser.parse_args()
    return args


def testInput(number, name, project, timeEstimation, DDL, remarks):
    """ test the form of the input
    """
    pass


def main():
    global sections
    # sections = loadSection()
    # addEntry(name, project, timeEstimation, DDL, remarks)
    #sections = {"sections": [{"Number": "00001", "Name": "testname1", "Project": "Mathe", "Time Estimation": "2", "DDL": "2020-06-12", "Remarks": "test"}]}
    args = cli()
    if os.path.exists(storedPath):
        sections = loadSection()
    if args.a:
        number = args.a[0]
        name = args.a[1]
        project = args.a[2]
        timeEstimation = args.a[3]
        DDL = args.a[4]
        remarks = args.a[5]
        testInput(number, name, project, timeEstimation, DDL, remarks)
        addEntry(number, name, project, timeEstimation, DDL, remarks)
    printEntry()
    writeEntry()
    return 0


if __name__ == "__main__":
    main()


# YET TO BUILD:
# testInput (with python raise exceptions, help ensure input quality)
# delete entries and clear the whole database (with warnings)
# modiry entries 
# database robustness: the mechanism to allow modify the basic sections
#    (maybe add more than the names later, so change them into more
#    flexible sections)
# better UI
# interactive software (like khal)




# techniques used:
# - json, for data process
# - format alignment and colored printing
# - sty, for colors
# - argParse, for cli
